version: '2'
services:
  springbootrestapiangular-app:
    image: springbootrestapiangular
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://springbootrestapiangular-mysql:3306/springbootrestapiangular?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  springbootrestapiangular-mysql:
    extends:
      file: mysql.yml
      service: springbootrestapiangular-mysql
